Ot138 22 footer
alkemyTech/OT138-CLIENT pull request #16
Opened 2022-02-22 03:03 UTC by Agustin-Q

2022-02-22 18:07 UTC, facundojuarez2k requested changes
Marqué unos detalles que habría que cambiar. De todas formas el endpoint de public data no maneja errores por el momento, por lo cual este código funcionaría bien.

2022-02-22 18:07 UTC, facundojuarez2k commented on src/services/requests/publicData.js
> +      result.errorMessage = response.message;
El objeto response no tiene las propiedades _error_ y _message_, estas deberían estar definidas en response.data (actualmente el endpoint API_PUBLIC_DATA solo retorna el contenido de publicData).

Referencia: https://axios-http.com/docs/res_schema

2022-02-23 01:02 UTC, Agustin-Q commented on src/constants/urls.js
> +export const API_PUBLIC_DATA = "/api/organizations/1/public";
Listo ya lo corregí, yo tenia mal la variable de entorno REACT_APP_API_URL, la tenia con http://localhost:4000/ y tiene que ser http://localhost:4000/api/

2022-02-23 01:03 UTC, Agustin-Q commented on src/services/requests/publicData.js
> +      result.errorMessage = response.message;
corregido ahora saco directamente la propiedad data de la respuesta.

2022-02-23 16:46 UTC, facundojuarez2k approved these changes

2022-02-23 16:46 UTC, merged